apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: campusg
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgres
  clusterIP: None  # Headless service for StatefulSet
