# Modified docker-compose.clerk-test.yml
services:
  # Database for the user service
  postgres-user:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # User service
  user-service:
    build: 
      context: ./services/user-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-user:5432/user_service_db
      DB_HOST: postgres-user
      DB_PORT: 5432
      DB_NAME: user_service_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5000:5000"
    depends_on:
      postgres-user:
        condition: service_healthy
    volumes:
      - ./services/user-service:/app
      
volumes:
  postgres_user_data:
