apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: campusg
data:
  # Only keep essential configuration for the Order Service
  # Service URLs removed as they're now only needed by saga orchestrators
  database_url: "postgresql://postgres:postgres@postgres:5432/order_db"
  kafka_brokers: "kafka:29092"
  flask_env: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  namespace: campusg
type: Opaque
data:
  # Default value: "dev-key-please-change-in-production" (base64 encoded)
  secret_key: ZGV2LWtleS1wbGVhc2UtY2hhbmdlLWluLXByb2R1Y3Rpb24=
