apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: campusg
  labels:
    app: order-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: order-service
  type: ClusterIP
