apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: campusg
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: user-service
