apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: campusg
data:
  user_service_url: "http://user-service:3000"
  order_service_url: "http://order-service:3000"
  payment_service_url: "http://payment-service:3000"
  node_env: "production"
